"""
ESCOPO DE VARIÁVEIS
globais - É VISUALIZADA POR TODO O PROGRAMA.
locais - EXIBIDA SOMENTE DENTRO DAQUELE BLOCO DE DECLARAÇÃO
EXEMPLOS JAVA E C
INT NUMER = 35
EXEMPLO NO PYTHON
NUMER = 53
{NÃO É NECESSARIO DECLARAR O TIPO DA VARIÁVEL NO PYTHON}
"""

print('@@@Escopo de Variáveis@@@')
print('Globais e Locais')
